# Generated by Django 5.2.6 on 2025-10-11 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExecutionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
                ('delivery_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='CustomerStats.deliverytype')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('video_path', models.CharField(max_length=255)),
                ('volume_mm3', models.FloatField()),
                ('price_usd', models.FloatField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CustomerStats.client')),
                ('delivery_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='CustomerStats.deliverytype')),
                ('execution_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='CustomerStats.executiontype')),
            ],
        ),
    ]
