# Generated by Django 5.2.6 on 2025-09-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerStats', '0003_alter_order_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='delivery_type',
            field=models.CharField(choices=[('post', 'post'), ('taxi', 'taxi'), ('courier', 'courier')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('post', 'post'), ('taxi', 'taxi'), ('courier', 'courier')], max_length=100, null=True),
        ),
    ]
