# Generated by Django 5.2.6 on 2025-09-20 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerStats', '0006_deliverytype_alter_client_delivery_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='delivery_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='CustomerStats.deliverytype'),
        ),
        migrations.AlterField(
            model_name='deliverytype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='CustomerStats.deliverytype'),
        ),
    ]
