# Generated by Django 5.2.6 on 2025-09-20 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerStats', '0007_alter_client_delivery_type_alter_deliverytype_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='video_path',
        ),
    ]
