# Generated by Django 5.2.6 on 2025-09-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CustomerStats", "0008_rename_name_order_video_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="execution_type",
            field=models.CharField(
                choices=[
                    ("wax", "wax"),
                    ("polymer", "polymer"),
                    ("laser", "laser"),
                    ("casting", "casting"),
                    ("default", "empty"),
                ],
                default="default",
                max_length=100,
            ),
        ),
    ]
