# Generated by Django 5.2.6 on 2025-09-20 13:19

from django.db import migrations

def set_execution_type(apps, schema_editor):
    Order = apps.get_model("CustomerStats", "Order")

# Масово оновити всі існуючі замовлення
    Order.objects.filter(execution_type='default').update(execution_type='casting')

# Можеш змінити 'casting' на будь-яке інше значення з EXECUTION_TYPE


class Migration(migrations.Migration):

    dependencies = [
        ("CustomerStats", "0009_order_execution_type"),
    ]

    operations = [
        migrations.RunPython(set_execution_type),
    ]
