# Generated by Django 5.2.6 on 2025-09-30 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerStats', '0009_client_user'),
        ('CustomerStats', '0011_executiontype_alter_order_execution_type'),
    ]

    operations = [
    ]
